apiVersion: "v1"
kind: Service
metadata:
  name: cinema-movie-show-db
spec:
  selector:
    app: cinema-movie-show-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32002
  type: NodePort

