apiVersion: "v1"
kind: Service
metadata:
  name: cinema-supplier-db
spec:
  selector:
    app: cinema-supplier-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32005
  type: NodePort

