apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: server-movie-show
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-movie-show
  template:
    metadata:
      labels:
        app: server-movie-show
    spec:
      containers:
        - name: server-movie-show
          image: vinhbh/cinema_movie_show_server:6.0
          ports:
            - containerPort: 8082

