FROM openjdk:17
EXPOSE 8080
ADD target/cinema_handle_import_movie_service-0.0.1-SNAPSHOT.jar cinema_handle_import_movie_service-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar", "/cinema_handle_import_movie_service-0.0.1-SNAPSHOT.jar"]