FROM openjdk:17
EXPOSE 8080
ADD target/cinema_movie_show_service-0.0.1-SNAPSHOT.jar cinema_movie_show_service-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar", "/cinema_movie_show_service-0.0.1-SNAPSHOT.jar"]