apiVersion: "v1"
kind: Service
metadata:
  name: cinema-user-db
spec:
  selector:
    app: cinema-user-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32003
  type: NodePort

