FROM openjdk:17
EXPOSE 8080
ADD target/cinema_supplier_service-0.0.1-SNAPSHOT.jar cinema_supplier_service-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar", "/cinema_supplier_service-0.0.1-SNAPSHOT.jar"]